vidaMaxima('Hobbit', -10)
vidaMaxima('Anao', 10)
vidaMaxima('Elfo', 0)
vidaMaxima('Gnomo', 0)
vidaMaxima('Humano', 0)
vidaMaxima('Ogro', 20)

forca('Hobbit', 0)
forca('Anao', 2)
forca('Elfo', 0)
forca('Gnomo', 0)
forca('Humano', 1)
forca('Ogro', 2)

inteligencia('Hobbit', 2)
inteligencia('Anao', 0)
inteligencia('Elfo', 2)
inteligencia('Gnomo', 3)
inteligencia('Humano', 1)
inteligencia('Ogro', 0)

sabedoria('Hobbit', 0)
sabedoria('Anao', 0)
sabedoria('Elfo', 2)
sabedoria('Gnomo', 0)
sabedoria('Humano', 1)
sabedoria('Ogro', 0)

destreza('Hobbit', 2)
destreza('Anao', 0)
destreza('Elfo', 2)
destreza('Gnomo', 3)
destreza('Humano', 1)
destreza('Ogro', 0)

constituicao('Hobbit', 0)
constituicao('Anao', 2)
constituicao('Elfo', 0)
constituicao('Gnomo', 0)
constituicao('Humano', 1)
constituicao('Ogro', 2)

carisma('Hobbit', 3)
carisma('Anao', 1)
carisma('Elfo', 0)
carisma('Gnomo', 0)
carisma('Humano', 1)
carisma('Ogro', 0)